# Generated by Django 4.2.1 on 2023-06-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/')),
            ],
        ),
    ]
