# Generated by Django 4.2.1 on 2023-06-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.ManyToManyField(blank=True, to='store.section'),
        ),
    ]
