# Generated by Django 4.2.1 on 2023-06-26 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
