# Generated by Django 4.2.1 on 2023-07-06 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cupon',
        ),
    ]
