# Generated by Django 4.2.1 on 2023-07-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_delete_cupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='applied_coupon',
        ),
    ]
