# Generated by Django 4.2.1 on 2023-07-08 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_headline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Headline',
        ),
    ]
