# Generated by Django 4.2.1 on 2023-07-08 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_delete_headline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
