# Generated by Django 4.2.1 on 2023-07-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('portfolio_link', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('whatsapp_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
